module Stoplight
  module Domain
    module Strategies
      class GreenRunStrategy
        include _RunStrategy

        attr_reader request_tracker: Tracker::Request
        attr_reader config: Config

        def initialize: (config: Config, request_tracker: Tracker::Request) -> void

        def record_error: (StandardError) -> void
        def record_success: -> void
      end
    end
  end
end
