module Stoplight
  module Domain
    module Strategies
      class GreenRunStrategy
        include _RunStrategy

        attr_reader request_tracker: Tracker::Request
        @run_recorder: Telemetry::RunRecorder
        @clock: _Clock

        def initialize: (request_tracker: Tracker::Request,
            run_recorder: Telemetry::RunRecorder, clock: _Clock) -> void

        def capture_started_at: () -> Float?
        def duration_since: (Float?) -> Float?

        def record_error: (StandardError, duration_ms: Float?, fallback_used: bool) -> void
        def record_success: (duration_ms: Float?, ?error: StandardError?)-> void
      end
    end
  end
end
