module Stoplight
  module Domain
    module Strategies
      class YellowRunStrategy
        include _RunStrategy

        attr_reader state_store: Domain::_StateStore
        attr_reader metrics_store: _MetricsStore
        attr_reader recovery_lock_store: _RecoveryLockStore
        attr_reader notifiers: Array[state_transition_notifier]
        attr_reader request_tracker: Tracker::RecoveryProbe
        attr_reader red_run_strategy: RedRunStrategy

        @name: String
        @error_tracking_policy: ErrorTrackingPolicy

        def initialize: (
          name: String,
          error_tracking_policy: ErrorTrackingPolicy,
          notifiers: Array[state_transition_notifier],
          request_tracker: Tracker::RecoveryProbe,
          red_run_strategy: RedRunStrategy,
          state_store: Domain::_StateStore,
          metrics_store: _MetricsStore,
          recovery_lock_store: _RecoveryLockStore
        ) -> void

        def with_recovery_lock: [T] (
            fallback: (^(StandardError?) -> T)?,
            state_snapshot: StateSnapshot,
            code: ^() -> T,
          ) { () -> T } -> T

        def record_recovery_probe_success: () -> void
        def record_recovery_probe_failure: (StandardError) -> void
        def enter_recovery: (StateSnapshot) -> void
      end
    end
  end
end
