# frozen_string_literal: true

module Stoplight
  module Infrastructure
    module Memory
      class DataStore
        class RecoveryLockToken
          include Domain::_RecoveryLockToken

          attr_reader light_name: String

          def initialize: (light_name: String) -> void
        end
      end
    end
  end
end
