# frozen_string_literal: true

module Stoplight
  module Infrastructure
    module Memory
      class DataStore
        class State
          attr_accessor recovered_at: Time?
          attr_accessor locked_state: state
          attr_accessor recovery_scheduled_after: Time?
          attr_accessor recovery_started_at: Time?
          attr_accessor breached_at: Time?

          def initialize: -> void
        end
      end
    end
  end
end
