AllCops:
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'stoplight.gemspec'

Lint/MissingSuper:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
