AllCops:
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'stoplight.gemspec'
    - 'lib/stoplight/rspec/**/*'

Lint/MissingSuper:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
    - 'lib/stoplight/rspec/**/*'

Metrics/ClassLength:
  Enabled: true
  Max: 110

Layout/BlockAlignment:
  Exclude:
    - 'spec/support/**/*'
    - 'lib/stoplight/rspec/**/*'
