require:
  - ./rubocop/stoplight/architecture_boundaries.rb

Stoplight/ArchitectureBoundaries:
  Enabled: true
  Severity: error
  Include:
    - 'lib/stoplight/domain/**/*.rb'
    - 'lib/stoplight/infrastructure/**/*.rb'
    - 'lib/stoplight/wiring/**/*.rb'
    - 'lib/stoplight/admin/**/*.rb'
    - 'spec/stoplight/domain/**/*_spec.rb'
    - 'spec/stoplight/infrastructure/**/*_spec.rb'
    - 'spec/stoplight/wiring/**/*_spec.rb'
    - 'spec/stoplight/admin/**/*_spec.rb'
