module Stoplight
  module Infrastructure
    module Redis
      module Storage
        class KeySpace
          def system_id: -> String
          def light_id: -> String

          def self.build: (system_name: _ToS, light_name: _ToS) -> KeySpace

          def self.hash_name: (_ToS) -> String

          def initialize: (system_id: String, light_id: String) -> void
          def key: (*_ToS) -> String
        end
      end
    end
  end
end
