module Stoplight
  module Infrastructure
    module Redis
      module Storage
        class Metrics
          include Domain::_MetricsStore

          def serialize_exception: (StandardError, timestamp: Float) -> String

          def deserialize_failure: (String?) -> Domain::Failure?

          private def metrics_ttl: -> Integer
        end
      end
    end
  end
end
