module Stoplight
  module Infrastructure
    module Redis
      module Storage
        class RecoveryLock
          include Domain::_RecoveryLockStore

          attr_reader config: Domain::Config
          attr_reader redis: redis
          attr_reader scripting: Scripting
          attr_reader key_space: Key

          def initialize: (
            config: Domain::Config,
            redis: redis,
            scripting: Scripting,
            key_space: Key
          ) -> void

          def lock_key: -> String
          def lock_timeout: -> Integer
        end
      end
    end
  end
end
