module Stoplight
  module Infrastructure
    module Storage
      class CompatibilityMetrics < Domain::Storage::Metrics
        private attr_reader data_store: Domain::DataStore
        private attr_reader config: Domain::Config

        def initialize: (
          data_store: Domain::DataStore,
          config: Domain::Config,
        ) -> void
      end
    end
  end
end
