module Stoplight
  module Infrastructure
    module Storage
      class CompatibilityRecoveryLock[Token < Domain::RecoveryLockToken] < Domain::Storage::RecoveryLock[Token]
        private attr_reader data_store: Domain::DataStore[Token]
        private attr_reader config: Domain::Config

        def initialize: (data_store: Domain::DataStore[Token], config: Domain::Config) -> void
      end
    end
  end
end
