module Stoplight
  module Domain
    module Color
      type green = "green"
      type yellow = "yellow"
      type red = "red"

      GREEN: green
      YELLOW: yellow
      RED: red
    end

    type color = Color::green | Color::yellow | Color::red
  end
end
