module Stoplight
  module Domain
    class Config < Data
      def self.empty: () -> Config

      attr_reader threshold: threshold
      attr_reader window_size: Integer?
      attr_reader tracked_errors: Array[StandardError]
      attr_reader skipped_errors: Array[StandardError]
      attr_reader name: String
      attr_reader cool_off_time: Integer
      attr_reader recovery_threshold: Integer

      def initialize: (**config_params) -> void

      def track_error?: ((Class)  error) -> bool

      def cool_off_time_in_milliseconds: () -> Integer

      def with: (**config_overrides) -> Config
    end
  end
end
