module Stoplight
  module Domain
    class Config < Data
      attr_reader threshold: percentage | Integer
      attr_reader window_size: duration_seconds?
      attr_reader tracked_errors: Array[Module]
      attr_reader skipped_errors: Array[Module]
      attr_reader name: String
      attr_reader cool_off_time: duration_seconds
      attr_reader recovery_threshold: Integer
      attr_reader traffic_control: _TrafficControl
      attr_reader traffic_recovery: _TrafficRecovery
      attr_reader error_notifier: error_notifier
      attr_reader notifiers: Array[_StateTransitionNotifier]
      attr_reader data_store: _DataStore

      def self.new: (
          name: String,
          cool_off_time: duration_seconds,
          threshold: percentage | Integer,
          recovery_threshold: Integer,
          window_size: duration_seconds?,
          tracked_errors: Array[Module],
          skipped_errors: Array[Module],
          traffic_control: _TrafficControl,
          traffic_recovery: _TrafficRecovery,
          error_notifier: error_notifier,
          notifiers: Array[_StateTransitionNotifier],
          data_store: _DataStore
        ) -> instance

      def initialize: (
          name: String,
          cool_off_time: duration_seconds,
          threshold: percentage | Integer,
          recovery_threshold: Integer,
          window_size: duration_seconds?,
          tracked_errors: Array[Module],
          skipped_errors: Array[Module],
          traffic_control: _TrafficControl,
          traffic_recovery: _TrafficRecovery,
          error_notifier: error_notifier,
          notifiers: Array[_StateTransitionNotifier],
          data_store: _DataStore
        ) -> void

      def cool_off_time_in_milliseconds: () -> Integer

      def with: (
          ?name: optional[String],
          ?cool_off_time: optional[duration_seconds],
          ?threshold: optional[percentage | Integer],
          ?recovery_threshold: optional[Integer],
          ?window_size: optional[duration_seconds?],
          ?tracked_errors: optional[Array[Module]],
          ?skipped_errors: optional[Array[Module]],
          ?traffic_control: optional[_TrafficControl],
          ?traffic_recovery: optional[_TrafficRecovery],
          ?error_notifier: optional[error_notifier],
          ?notifiers: optional[Array[_StateTransitionNotifier]],
          ?data_store: optional[_DataStore],
      ) -> Config | () -> Config
    end
  end
end
