# frozen_string_literal: true

module Stoplight
  module Domain
    class DataStore[T < RecoveryLockToken]
      METRICS_RETENTION_TIME: Integer

      def names: -> Array[String]

      def get_metrics: (Config config) -> Domain::Metrics

      def get_recovery_metrics: (Config config) -> Domain::Metrics

      def get_state_snapshot: (Config config) -> StateSnapshot

      def clear_metrics: (Config config) -> void

      def clear_recovery_metrics: (Config config) -> void

      def record_failure: (Config config, StandardError exception) -> void

      def record_success: (Config config) -> void

      def record_recovery_probe_failure: (Config config, StandardError exception) -> void

      def record_recovery_probe_success: (Config config) -> void

      def set_state: (Config config, state state) -> state

      def acquire_recovery_lock: (Config config) -> T?

      def release_recovery_lock: (T lock) -> void

      def transition_to_color: (Config config, color color) -> bool

      def delete_light: (Config config) -> void
    end
  end
end
