module Stoplight
  module Domain
    class Failure
      attr_reader error_class: String
      attr_reader error_message: String
      attr_reader time: Time
      alias occurred_at time

      def self.from_error: (StandardError error, time: Time) -> instance

      def initialize: (String error_class, String error_message, Time time) -> void

      def ==: (untyped other) -> bool
    end
  end
end
