module Stoplight
  module Domain
    class Light
      attr_reader config: Config
      attr_reader green_run_strategy: Strategies::GreenRunStrategy
      attr_reader yellow_run_strategy: Strategies::YellowRunStrategy[RecoveryLockToken]
      attr_reader red_run_strategy: Strategies::RedRunStrategy
      attr_reader state_store: Storage::State
      attr_reader factory: LightFactory

      def initialize: (
        Config config,
        green_run_strategy: Strategies::GreenRunStrategy,
        yellow_run_strategy: Strategies::YellowRunStrategy[RecoveryLockToken],
        red_run_strategy: Strategies::RedRunStrategy,
        factory: LightFactory,
        state_store: Storage::State
      ) -> void

      def name: -> String

      def state: -> state

      def color: -> color

      def run: [T] (?(^(StandardError?) -> T)?) { () -> T } -> T

      def lock: (color color) -> Light

      def unlock: -> Light

      def ==: (untyped) -> bool

      private def state_strategy_factory: (color color) -> Strategies::RunStrategy
      private def state_snapshot: -> StateSnapshot
    end
  end
end
