module Stoplight
  module Domain
    class LightFactory
      def with: (
          ?name: String | undefined,
          ?cool_off_time: cool_off_time | undefined,
          ?threshold: threshold | undefined,
          ?recovery_threshold: recovery_threshold | undefined,
          ?window_size: window_size | undefined,
          ?tracked_errors: errors | undefined,
          ?skipped_errors: errors | undefined,
          ?error_notifier: error_notifier | undefined,
          ?notifiers: notifiers | undefined,
          ?data_store: data_store | undefined,
          ?traffic_control: traffic_control | undefined,
          ?traffic_recovery: traffic_recovery | undefined,
      ) -> LightFactory

      def build: -> Light

      def build_with: (
          name: String | undefined,
          cool_off_time: cool_off_time | undefined,
          threshold: threshold | undefined,
          recovery_threshold: recovery_threshold | undefined,
          window_size: window_size | undefined,
          tracked_errors: errors | undefined,
          skipped_errors: errors | undefined,
          error_notifier: error_notifier | undefined,
          notifiers: notifiers | undefined,
          data_store: data_store | undefined,
          traffic_control: traffic_control | undefined,
          traffic_recovery: traffic_recovery | undefined,
      ) -> Light
    end
  end
end
