module Stoplight
  module Domain
    class LightInfo < Data
      include _LightInfo

      def self.new: (
          name: String,
        ) -> instance

      def initialize: (
          name: String,
        ) -> void
    end
  end
end
