module Stoplight
  module Domain
    class Metrics < Data
      def successes: -> Integer?
      def successes!: -> Integer
      def errors!: -> Integer
      def errors: -> Integer?
      def consecutive_errors: -> Integer
      def consecutive_successes: -> Integer
      def last_error: -> Failure?
      def last_success_at: -> Time?

      def initialize: (
        successes: Integer?,
        errors: Integer?,
        consecutive_errors: Integer,
        consecutive_successes: Integer,
        last_error: Failure?,
        last_success_at: Time?
      ) -> void

      def error_rate: () -> Float?

      def requests: () -> Integer?

      def last_error_at: () -> Time?
    end
  end
end
