module Stoplight
  module Domain
    module State
      type unlocked = "unlocked"
      type locked_green = "locked_green"
      type locked_red = "locked_red"

      UNLOCKED: unlocked
      LOCKED_GREEN: locked_green
      LOCKED_RED: locked_red
    end

    type state = State::unlocked | State::locked_green | State::locked_red
  end
end
