module Stoplight
  module Domain
    type timestamp = Float | Integer
    type duration_seconds = Float | Integer
    type duration_ms = Float

    # Light Colors
    type green = "green"
    type yellow = "yellow"
    type red = "red"
    type color = green | yellow | red

    # Light States
    type unlocked = "unlocked"
    type locked_green = "locked_green"
    type locked_red = "locked_red"
    type state = unlocked | locked_green | locked_red

    type recovery_decision = :green | :yellow | :red
    type error_notifier = ^(StandardError) -> void

    # Percentage as decimal (0.0 to 1.0)
    type percentage = Float
  end
end
