module Stoplight
  module Infrastructure
    module Storage
      module Redis
        class Metrics < Domain::Storage::Metrics
          def serialize_exception: (StandardError, timestamp: Float) -> String

          def deserialize_failure: (String?) -> Domain::Failure?

          private def metrics_ttl: -> Integer
        end
      end
    end
  end
end
