module Stoplight
  module Infrastructure
    module Storage
      module Redis
        class Scripting < Infrastructure::Redis::DataStore::Scripting
          SCRIPTS_ROOT: String

          def default_scripts_root: -> String
        end
      end
    end
  end
end
