module Stoplight
  module Infrastructure
    module DataStore
      class Redis
        class RecoveryLockToken < Domain::RecoveryLockToken
          attr_reader light_name: String

          attr_reader token: String

          def initialize: (light_name: String) -> void

          def lock_key: -> String

          private def key: (*_ToS) -> String
        end
      end
    end
  end
end
