module Stoplight
  module Infrastructure
    module DataStore
      class Redis
        class RecoveryLockStore
          attr_reader redis: redis

          attr_reader lock_timeout: Integer
          attr_reader scripting: Scripting

          def initialize: (
            redis: redis,
            lock_timeout: Integer,
            scripting: Scripting
          ) -> void

          def acquire_lock: (String light_name) -> RecoveryLockToken?

          def release_lock: (RecoveryLockToken recovery_lock) -> void
        end
      end
    end
  end
end
