module Stoplight
  module Infrastructure
    module DataStore
      class Redis
        class Scripting
          SCRIPTS_ROOT: String

          def self.default_scripts_root: -> String

          attr_reader scripts_root: String

          attr_reader shas: Hash[Symbol, String]

          attr_reader redis: ::Redis | ConnectionPool[::Redis]

          def initialize: (
            redis: ::Redis | ConnectionPool[::Redis],
            scripts_root: String,
          ) -> void

          def call: (
            (String | Symbol) script_name,
            keys: Array[String],
            args: Array[String]
          ) -> void

          private def reload_script: (String script_name) -> String

          private def script_sha: (String script_name) -> String
        end
      end
    end
  end
end
