module Stoplight
  module Wiring
    class System
      class Storage
        @system_id: String
        @system_name: String
        @failover_system: _System
        @factories: Hash[Domain::Config, LightFactory]
        @telemetry: Domain::_TelemetryPublisher

        def initialize: (
            system_id: String,
            system_name: String,
            failover_system: _System,
            telemetry: Domain::_TelemetryPublisher
          ) -> void

        def state_snapshot: (Domain::Config) -> Domain::StateSnapshot
        def metrics_snapshot: (Domain::Config) -> Domain::MetricsSnapshot
        def delete: (Domain::Config) -> void
        def lock: (Domain::Config, Domain::color) -> void
        def unlock: (Domain::Config) -> void

        private

        def state_store: (Domain::Config) -> Domain::_StateStore
        def metrics_store: (Domain::Config) -> Domain::_MetricsStore
        def lock_control: (Domain::Config) -> Domain::LockControl
        def light_factory: (Domain::Config) -> LightFactory
      end
    end
  end
end
