module Stoplight
  module Domain
    module Tracker
      class RecoveryProbe
        attr_reader traffic_recovery: _TrafficRecovery
        attr_reader notifiers: Array[_StateTransitionNotifier]
        attr_reader config: Config
        attr_reader metrics_store: _MetricsStore
        attr_reader state_store: _StateStore
        attr_reader emitter: Telemetry::Emitter

        def initialize: (
          config: Config,
          traffic_recovery: _TrafficRecovery,
          notifiers: Array[_StateTransitionNotifier],
          metrics_store: _MetricsStore,
          state_store: _StateStore,
          emitter: Telemetry::Emitter,
        ) -> void

        def record_failure: (StandardError exception) -> void
        def record_success: -> void
        def recover: -> void
      end
    end
  end
end
