module Stoplight
  module Domain
    module Tracker
      class RecoveryProbe
        attr_reader traffic_recovery: _TrafficRecovery
        attr_reader notifiers: Array[state_transition_notifier]
        attr_reader config: Config
        attr_reader metrics_store: _MetricsStore
        attr_reader state_store: _StateStore

        def initialize: (
          config: Config,
          traffic_recovery: _TrafficRecovery,
          notifiers: Array[state_transition_notifier],
          metrics_store: _MetricsStore,
          state_store: _StateStore,
        ) -> void

        def record_failure: (StandardError exception) -> void
        def record_success: -> void
        def recover: -> void
      end
    end
  end
end
