module Stoplight
  module Domain
    module Tracker
      class RecoveryProbe
        attr_reader traffic_recovery: _TrafficRecovery
        attr_reader config: Config
        attr_reader metrics_store: _MetricsStore
        attr_reader state_store: _StateStore
        attr_reader emitter: Telemetry::Emitter

        def initialize: (
          config: Config,
          traffic_recovery: _TrafficRecovery,
          metrics_store: _MetricsStore,
          state_store: _StateStore,
          emitter: Telemetry::Emitter,
        ) -> void

        def record_failure: (StandardError exception, duration_ms: Float) -> void
        def record_success: (duration_ms: Float) -> void

        private

        def recover: (duration_ms: Float, exception: StandardError?) -> void
        def transition: (to_color: color) -> bool
      end
    end
  end
end
