module Stoplight
  module Domain
    module Tracker
      class Request
        attr_reader config: Config
        attr_reader traffic_control: _TrafficControl
        attr_reader notifiers: Array[_StateTransitionNotifier]
        attr_reader metrics_store: _MetricsStore
        attr_reader state_store: _StateStore
        attr_reader emitter: Telemetry::Emitter

        def initialize: (
          config: Config,
          traffic_control: _TrafficControl,
          notifiers: Array[_StateTransitionNotifier],
          metrics_store: _MetricsStore,
          state_store: _StateStore,
          emitter: Telemetry::Emitter,
        ) -> void

        def record_failure: (StandardError exception) -> void
        def record_success: -> void

        private def transition_to_red: (StandardError exception, metrics: MetricsSnapshot) -> void
      end
    end
  end
end
