module Stoplight
  module Domain
    module Tracker
      class Request < Base
        attr_reader config: Domain::Config
        attr_reader traffic_control: TrafficControl::Base
        attr_reader notifiers: Array[StateTransitionNotifier]
        attr_reader metrics_store: Storage::Metrics
        attr_reader state_store: Storage::State

        def initialize: (
          config: Domain::Config,
          traffic_control: TrafficControl::Base,
          notifiers: Array[StateTransitionNotifier],
          metrics_store: Storage::Metrics,
          state_store: Storage::State,
        ) -> void

        def record_failure: (StandardError exception) -> void
        def reucord_success: -> void

        private def transition_to_red: (StateSnapshot exception, metrics: Domain::Metrics) -> void
      end
    end
  end
end
