module Stoplight
  module Infrastructure
    module Redis
      module Storage
        class Registry
          include Domain::_Registry

          REDIS_KEY: String
          @redis: redis
          @key_space: SystemKeySpace
          @clock: Domain::_Clock
          @config_serializer: singleton(ConfigSerializer)

          def initialize: (
              redis: redis,
              key_space: SystemKeySpace,
              clock: Domain::_Clock,
              config_serializer: singleton(ConfigSerializer),
            ) -> void

          private

          def key: () -> String
        end
      end
    end
  end
end
