# frozen_string_literal: true

module Stoplight
  module Infrastructure
    module Memory
      module Storage
        class Registry
          include Domain::_Registry
        end
      end
    end
  end
end
