module Stoplight
  module Infrastructure
    module Memory
      module Storage
        class WindowMetrics < Domain::Storage::Metrics
          attr_reader mutex: Mutex
          attr_reader clock: Domain::Clock

          @window_size: Integer
          @consecutive_errors: Integer
          @consecutive_successes: Integer
          @last_error: Domain::Failure?
          @last_success_at: Time?
          @successes: Infrastructure::Memory::DataStore::SlidingWindow
          @errors: Infrastructure::Memory::DataStore::SlidingWindow

          def initialize: (window_size: Integer, clock: Domain::Clock) -> void

          def initialize_metrics: -> void
        end
      end
    end
  end
end
