module Stoplight
  module Wiring
    class DataStoreBackend
      def windowed_metrics_store: -> Domain::Storage::Metrics
      def unbounded_metrics_store: -> Domain::Storage::Metrics
      def recovery_metrics_store: -> Domain::Storage::Metrics
      def state_store: -> Domain::Storage::State
      def recovery_lock_store: -> Domain::Storage::RecoveryLock
    end
  end
end
