module Stoplight
  module Wiring
    class DefaultConfiguration
      @cool_off_time: option[cool_off_time]
      @threshold: option[threshold]
      @recovery_threshold: option[recovery_threshold]
      @window_size: option[window_size]
      @tracked_errors: option[errors]
      @skipped_errors: option[errors]
      @traffic_control: option[traffic_control]
      @traffic_recovery: option[traffic_recovery]
      @error_notifier: option[error_notifier]
      @data_store: option[data_store]
      @notifiers: option[notifiers]

      def to_settings: -> Settings

      def cool_off_time: -> cool_off_time
      def threshold: -> threshold
      def recovery_threshold: -> recovery_threshold
      def window_size: -> window_size
      def tracked_errors: -> errors
      def skipped_errors: -> errors
      def traffic_control: -> traffic_control
      def traffic_recovery: -> traffic_recovery
      def error_notifier: -> error_notifier
      def data_store: -> data_store
      def notifiers: -> notifiers

      def cool_off_time=: (cool_off_time) -> void
      def threshold=: (threshold) -> void
      def recovery_threshold=: (recovery_threshold) -> void
      def window_size=: (window_size) -> void
      def tracked_errors=: (errors) -> void
      def skipped_errors=: (errors) -> void
      def traffic_control=: (traffic_control) -> void
      def traffic_recovery=: (traffic_recovery) -> void
      def error_notifier=: (error_notifier) -> void
      def data_store=: (data_store) -> void
      def notifiers=: (notifiers) -> void
    end
  end
end
