module Stoplight
  module Wiring
    module Default
      COOL_OFF_TIME: cool_off_time

      DATA_STORE: data_store

      ERROR_NOTIFIER: error_notifier

      FORMATTER: Infrastructure::notification_formatter

      NOTIFIERS: notifiers

      THRESHOLD: threshold
      RECOVERY_THRESHOLD: recovery_threshold

      WINDOW_SIZE: window_size

      TRACKED_ERRORS: errors
      SKIPPED_ERRORS: errors

      TRAFFIC_CONTROL: Domain::TrafficControl::Base
      TRAFFIC_RECOVERY: Domain::TrafficRecovery::Base
    end
  end
end
