module Stoplight
  module Wiring
    module Default
      COOL_OFF_TIME: duration

      DATA_STORE: data_store

      ERROR_NOTIFIER: error_notifier

      FORMATTER: notification_formatter

      NOTIFIERS: Array[state_transition_notifier]

      THRESHOLD: percentage | Integer
      RECOVERY_THRESHOLD: Integer

      WINDOW_SIZE: duration?

      TRACKED_ERRORS: Array[Module]
      SKIPPED_ERRORS: Array[Module]

      TRAFFIC_CONTROL: Domain::_TrafficControl
      TRAFFIC_RECOVERY: Domain::_TrafficRecovery
    end
  end
end
