module Stoplight
  module Wiring
    class DefaultConfiguration
      @config: Domain::Config
      @cool_off_time: optional[Domain::duration_seconds]
      @threshold: optional[Domain::percentage | Integer]
      @recovery_threshold: optional[Integer]
      @window_size: optional[Domain::duration_seconds?]
      @tracked_errors: optional[Array[Module] | Module]
      @skipped_errors: optional[Array[Module] | Module]
      @traffic_control: optional[traffic_control]
      @traffic_recovery: optional[traffic_recovery]
      @error_notifier: optional[Domain::error_notifier]
      @data_store: optional[Domain::_DataStore]
      @notifiers: optional[Array[Domain::_StateTransitionNotifier]]

      def to_config!: -> Domain::Config
      def notifiers: -> Array[Domain::_StateTransitionNotifier]
      def cool_off_time=: (Domain::duration_seconds) -> void
      def threshold=: (Domain::percentage | Integer) -> void
      def recovery_threshold=: (Integer) -> void
      def window_size=: (Domain::duration_seconds?) -> void
      def tracked_errors=: (Array[Module] | Module) -> void
      def skipped_errors=: (Array[Module] | Module) -> void
      def traffic_control=: (Wiring::traffic_control) -> void
      def traffic_recovery=: (Wiring::traffic_recovery) -> void
      def error_notifier=: (Domain::error_notifier) -> void
      def data_store=: (Domain::_DataStore) -> void
      def notifiers=:(Array[Domain::_StateTransitionNotifier]) -> void

      private

      def tracked_errors: -> optional[Array[Module]]
      def skipped_errors: -> optional[Array[Module]]
      def traffic_control: -> optional[Domain::_TrafficControl]
      def traffic_recovery: -> optional[Domain::_TrafficRecovery]
    end
  end
end
