module Stoplight
  module Wiring
    class GlobalState
      DEFAULT_SYSTEM_NAME: String

      @default_config: Domain::Config
      @default_system: Wiring::System
      @systems: Concurrent::Map[String, Wiring::System]

      attr_reader default_config: Domain::Config
      attr_reader default_system: Wiring::System

      def initialize: (default_config: Domain::Config) -> void
      def register_system: (
          _ToS name,
          ?cool_off_time: optional[Domain::duration_seconds],
          ?threshold: optional[Domain::percentage | Integer],
          ?recovery_threshold: optional[Integer],
          ?window_size: optional[Domain::duration_seconds?],
          ?tracked_errors: optional[Array[Module]],
          ?skipped_errors: optional[Array[Module]],
          ?data_store: optional[Domain::_DataStore],
          ?error_notifier: optional[Domain::error_notifier],
          ?notifiers: optional[Array[Domain::_StateTransitionNotifier]],
          ?traffic_control: optional[Wiring::traffic_control],
          ?traffic_recovery: optional[Wiring::traffic_recovery],
        ) -> Wiring::System

      private

      def register_system_with_config: (Domain::Config) -> Wiring::System

      def create_registry: (Domain::Config, Wiring::System) -> Domain::_Registry
    end
  end
end
