module Stoplight
  module Wiring
    class GlobalState
      DEFAULT_SYSTEM_NAME: String

      @default_config: Domain::Config
      @default_system: Wiring::System
      @systems: Concurrent::Map[String, Wiring::System]

      attr_reader default_config: Domain::Config
      attr_reader default_system: Wiring::System

      def initialize: (default_config: Domain::Config) -> void
      def create_system: (config: Domain::Config) -> Wiring::System

      def create_registry: (Domain::Config, Wiring::System) -> Domain::_Registry
    end
  end
end
