module Stoplight
  module Wiring
    class GlobalState
      DEFAULT_SYSTEM_NAME: String

      @default_config: Domain::Config
      @default_system: _System
      @systems: Concurrent::Map[String, _System]

      attr_reader default_config: Domain::Config
      attr_reader default_system: _System

      def initialize: (default_config: Domain::Config) -> void
      def create_system: (config: Domain::Config) -> _System

      def create_registry: (Domain::Config, _System) -> Domain::_Registry
    end
  end
end
