module Stoplight
  module Wiring
    class LightBuilder
      FAILOVER_DATA_STORE_CONFIG: Stoplight::DataStore::Memory
      MEMORY_REGISTRY: Concurrent::Map[Integer, Infrastructure::Memory::DataStore]

      attr_reader data_store_config: Domain::DataStoreConfig
      attr_reader error_notifier: error_notifier
      attr_reader traffic_recovery: traffic_recovery
      attr_reader traffic_control: traffic_control
      attr_reader config: Domain::Config
      attr_reader factory: untyped
      attr_reader clock: Domain::Clock

      def initialize: (Hash[Symbol, untyped]) -> void

      def build: -> Domain::Light

      def state_store: -> Domain::Storage::State
      def notifiers: -> Array[Domain::StateTransitionNotifier]
      def redis_recovery_lock_store: -> Infrastructure::Redis::DataStore::RecoveryLockStore
      def scripting: -> Infrastructure::Redis::DataStore::Scripting

      def memory_recovery_lock_store: -> Infrastructure::Memory::DataStore::RecoveryLockStore
      def failover_data_store: -> Domain::DataStore[Domain::RecoveryLockToken]
      def data_store: -> Domain::DataStore[Domain::RecoveryLockToken]

      def metrics_store: -> Domain::Storage::Metrics
      def recovery_lock_store: -> Domain::Storage::RecoveryLock[Domain::RecoveryLockToken]
      def request_tracker: -> Domain::Tracker::Request
      def recovery_probe_tracker: -> Domain::Tracker::RecoveryProbe
      def recovery_metrics_store: -> Domain::Storage::Metrics

      def green_run_strategy: -> Domain::Strategies::GreenRunStrategy
      def yellow_run_strategy: -> Domain::Strategies::YellowRunStrategy[Domain::RecoveryLockToken]
      def red_run_strategy: -> Domain::Strategies::RedRunStrategy
      def create_data_store: (Domain::DataStoreConfig data_store_config) -> Domain::DataStore[Domain::RecoveryLockToken]
      def memory_registry: -> Concurrent::Map[Integer, Infrastructure::Memory::DataStore]
    end
  end
end
