module Stoplight
  module Wiring
    class NotifierFactory
      def self.create: (
        notifier: Domain::_StateTransitionNotifier,
        error_notifier: Domain::error_notifier,
      ) -> Domain::_StateTransitionNotifier
    end
  end
end
