module Stoplight
  module Wiring
    module PublicApi
      Color: singleton(Domain::Color)
      Error: singleton(Domain::Error)
      State: singleton(Domain::State)

      module DataStore
        Base: singleton(Domain::DataStoreConfig)
        Redis: singleton(Wiring::DataStore::Redis)
        Memory: singleton(Wiring::DataStore::Memory)
      end

      module Notifier
        Base: singleton(Domain::StateTransitionNotifier)
        Generic: singleton(Infrastructure::Notifier::Generic)
        IO: singleton(Infrastructure::Notifier::IO)
        Logger: singleton(Infrastructure::Notifier::Logger)
      end
    end
  end
end
