module Stoplight
  module Wiring
    class System
      include _System

      @name: String
      @lights: Concurrent::Map[String, [Domain::Light, Integer, String?]]
      @failover_system: _System?
      @registry: Domain::_Registry
      @telemetry: Domain::Telemetry::Bus

      attr_reader system_config: Domain::Config

      def initialize: (config: Domain::Config, failover_system: _System?, registry: Domain::_Registry) -> void

      def __stoplight__storage: -> Storage
      def __stoplight__registry: -> Domain::_Registry
    end
  end
end
