module Stoplight
  module Wiring
    class SystemConfigurationDsl
      def initialize: (
        _ToS name,
        ?cool_off_time: optional[Domain::duration_seconds],
        ?threshold: optional[Domain::percentage | Integer],
        ?recovery_threshold: optional[Integer],
        ?window_size: optional[Domain::duration_seconds?],
        ?tracked_errors: optional[Array[Module] | Module],
        ?skipped_errors: optional[Array[Module] | Module],
        ?data_store: optional[Domain::_DataStore],
        ?error_notifier: optional[Domain::error_notifier],
        ?notifiers: optional[Array[Domain::_StateTransitionNotifier]],
        ?traffic_control: optional[traffic_control],
        ?traffic_recovery: optional[traffic_recovery],
      ) -> void

      def configure!: (Domain::Config default_config) -> Domain::Config

      private

      attr_reader name: String
      attr_reader cool_off_time: optional[Domain::duration_seconds]
      attr_reader threshold: optional[Domain::percentage | Integer]
      attr_reader recovery_threshold: optional[Integer]
      attr_reader window_size: optional[Domain::duration_seconds?]
      attr_reader data_store: optional[Domain::_DataStore]
      attr_reader error_notifier: optional[Domain::error_notifier]
      attr_reader notifiers: optional[Array[Domain::_StateTransitionNotifier]]
      attr_reader tracked_errors: optional[Array[Module]]
      attr_reader skipped_errors: optional[Array[Module]]
      attr_reader traffic_control: optional[Domain::_TrafficControl]
      attr_reader traffic_recovery: optional[Domain::_TrafficRecovery]
    end
  end
end
