# frozen_string_literal: true

module Stoplight
  module Infrastructure
    module DataStore
      class Memory
        class Metrics
          attr_accessor consecutive_errors: Integer
          attr_accessor consecutive_successes: Integer
          attr_accessor last_error: Domain::Failure?
          attr_accessor last_success_at: Time?

          def initialize: (
            consecutive_errors: Integer,
            consecutive_successes: Integer,
            last_error: Domain::Failure?,
            last_success_at: Time?
          ) -> void

          def last_error_at: -> Time?
        end
      end
    end
  end
end
