module Stoplight
  module Wiring
    module DataStore
      class Redis < Domain::DataStoreConfig
        attr_reader redis: redis
        attr_reader warn_on_clock_skew: bool

        def initialize: (redis redis, warn_on_clock_skew: bool) -> void
      end
    end
  end
end
