module Stoplight
  module Wiring
    class LightFactory
      class ConfigurationPipeline
        attr_reader settings: Settings

        def self.process: (settings: Settings) -> Domain::Config

        def initialize: (settings: Settings) -> void

        def process: -> Domain::Config

        def build_config: -> Domain::Config

        def build_dependencies: -> dependencies

        def base_config: -> Domain::Config

        private def name: -> String
        private def cool_off_time: -> cool_off_time
        private def threshold: -> threshold
        private def recovery_threshold: -> recovery_threshold
        private def window_size: -> window_size
        private def skipped_errors: -> errors
        private def tracked_errors: -> errors
        private def traffic_control: -> Domain::TrafficControl::Base
        private def traffic_recovery: -> Domain::TrafficRecovery::Base
        private def error_notifier: -> error_notifier
        private def notifiers: -> notifiers
        private def data_store: -> data_store
      end
    end
  end
end
