module Stoplight
  module Domain
    module Storage
      class State
        def state_snapshot: () -> StateSnapshot
        def set_state: (state) -> state
        def transition_to_color: (color) -> bool
        def clear: () -> void
      end
    end
  end
end
