module Stoplight
  module Infrastructure
    module FailSafe
      module Storage
        class Metrics
          include Domain::_MetricsStore

          attr_reader primary_store: Domain::_MetricsStore
          attr_reader error_notifier: Domain::error_notifier
          attr_reader failover_store: Domain::_MetricsStore
          attr_reader circuit_breaker: Domain::Light

          def initialize: (
            primary_store: Domain::_MetricsStore,
            error_notifier: Domain::error_notifier,
            failover_store: Domain::_MetricsStore,
            circuit_breaker: Domain::Light
          ) -> void

          def fallback: [T] { () -> T } -> ^(StandardError?) -> T
        end
      end
    end
  end
end
