module Stoplight
  module Infrastructure
    module FailSafe
      module Storage
        class RecoveryLockToken
          include Domain::_RecoveryLockToken

          attr_reader underlying_token: Domain::_RecoveryLockToken
          attr_reader origin: :primary | :failover

          def initialize: (
            underlying_token: Domain::_RecoveryLockToken,
            origin: (:primary | :failover)
          ) -> void
        end
      end
    end
  end
end
