module Stoplight
  module Infrastructure
    module FailSafe
      module Storage
        class Registry
          include Domain::_Registry

          @primary_registry: Domain::_Registry
          @error_notifier: Domain::error_notifier
          @failover_registry: Domain::_Registry
          @circuit_breaker: _Light

          def initialize: (
            primary_registry: Domain::_Registry,
            error_notifier: Domain::error_notifier,
            failover_registry: Domain::_Registry,
            circuit_breaker: _Light
          ) -> void
        end
      end
    end
  end
end
