module Stoplight
  class Admin
    class Dependencies
      @system: Wiring::System
      @storage: Wiring::System::Storage

      def initialize: (system: Wiring::System) -> void
      def config_registry: -> ConfigRegistry
      def lights_repository: -> LightsRepository
      def stats_action: -> Actions::Stats
      def unlock_action: -> Actions::Unlock
      def green_action: -> Actions::LockGreen
      def red_action: -> Actions::LockRed
      def green_all_action: -> Actions::LockAllGreen
      def remove_action: -> Actions::Remove
    end
  end
end
