module Stoplight
  class Admin
    module Helpers : Sinatra::Base
      COLORS: Array[Domain::color]

      def dependencies: -> Dependencies
      def system_url: (String system_id, String path) -> String
      def asset_path: (String) -> String
      def time_ago_in_words: (Time) -> String
      def control_attributes: (String href, ?confirm: String?, ?verb: String?) -> String
      def find_system: (String) -> Wiring::System
      def current_system_id: -> String
      def current_system: -> Wiring::System
      def show_system_switcher?: -> bool
    end
  end
end
