module Stoplight
  class Admin
    module Helpers : Sinatra::Base
      COLORS: Array[Domain::color]

      def dependencies: -> Dependencies
      def asset_path: (String) -> String
      def time_ago_in_words: (Time) -> String
      def control_attributes: (String href, ?confirm: String?, ?verb: String?) -> String
    end
  end
end
