module Stoplight
  class Admin
    class LightsStats
      EMPTY_STATS: Hash[Symbol, Integer]

      attr_reader lights: Array[LightView]
      @lights: Array[LightView]

      def self.call: (Array[LightView]) -> Hash[Symbol, Integer]

      def initialize: (Array[LightView]) -> void

      def call: -> Hash[Symbol, Integer]

      private

      def size: -> Integer

      def count_lights: (Domain::color)-> Integer
      def count_red: -> Integer
      def count_green: -> Integer
      def count_yellow: -> Integer

      def percent_lights: (Domain::color)-> Integer
      def percent_green: -> Integer
      def percent_red: -> Integer
      def percent_yellow: -> Integer
    end
  end
end
