module Stoplight
  class Admin
    class LightsRepository
      @registry: Domain::_Registry
      @storage: Wiring::System::Storage
      @system_config: Domain::Config

      def initialize: (
          registry: Domain::_Registry,
          storage: Wiring::System::Storage,
          system_config: Domain::Config
        ) -> void

      def all: -> Array[Light]
      def with_color: (*Domain::color) -> Array[Light]
      def lock: (String, ?Domain::color?) -> void
      def unlock: (String) -> void
      def remove: (String) -> void

      private

      def load_light_view: (String) -> Light
      def build_config: (String) -> Domain::Config
    end
  end
end
