module Stoplight
  class Admin
    class LightView
      COLORS: Array[Domain::color]

      attr_reader failures: Array[Domain::Failure]

      @state_snapshot: Domain::StateSnapshot
      @metrics_snapshot: Domain::MetricsSnapshot
      @recovery_metrics_snapshot: Domain::MetricsSnapshot
      @config: Domain::Config
      @failures: Array[Domain::Failure]

      def initialize: (
          config: Domain::Config,
          state_snapshot: Domain::StateSnapshot,
          recovery_metrics_snapshot: Domain::MetricsSnapshot,
          metrics_snapshot: Domain::MetricsSnapshot,
        ) -> void

      def id: -> String
      def color: -> Domain::color
      def name: -> String
      def state: -> Domain::state
      def failure_count: -> Integer
      def locked?: -> bool
      def unlocked?: -> bool
      def as_json: -> Hash[Symbol, _ToS]
      def default_sort_key: -> Array[Comparable]
      def last_check: -> Time?
      private def duration_in_words: (Integer) -> String
      def description_title: -> String
      def description_message: -> String
      def description_comment: -> String
      def latest_failure: -> Domain::Failure?
    end
  end
end
