module Stoplight
  class Admin
    class LightView
      COLORS: Array[Domain::color]

      attr_reader id: String
      attr_reader color: Domain::color
      attr_reader name: String

      @id: String
      @name: String
      @color: Domain::color
      @state: Domain::state
      @failures: Array[Domain::Failure]
      @failure_count: Integer?
      @latest_failure: Domain::Failure?
      @state_snapshot: Domain::StateSnapshot
      @recovery_metrics_snapshot: Domain::MetricsSnapshot?
      @config: Domain::Config

      def initialize: (
          id: String,
          config: Domain::Config,
          color: Domain::color,
          state: Domain::state,
          failures: Array[Domain::Failure],
          state_snapshot: Domain::StateSnapshot,
          recovery_metrics_snapshot: Domain::MetricsSnapshot?,
          ?failure_count: Integer?
        ) -> void

      def locked?: -> bool
      def unlocked?: -> bool
      def as_json: -> Hash[Symbol, _ToS]
      def default_sort_key: -> Array[Comparable]
      def last_check: -> Time?
      private def duration_in_words: (Integer) -> String
      def description_title: -> String
      def description_message: -> String
      def description_comment: -> String
    end
  end
end
