# frozen_string_literal: true

module Stoplight
  module Wiring
    class LightFactory
      class CompatibilityValidator
        attr_reader config: Domain::Config

        def self.call: (config: Domain::Config) -> void

        def initialize: (config: Domain::Config) -> void

        def call: -> void

        private def validate_traffic_control!: -> void

        def validate_traffic_recovery!: -> void
      end
    end
  end
end
