module Stoplight
  module Wiring
    class LightFactory
      class ConfigurationPipeline
        attr_reader settings: Settings

        def self.process: (settings: Settings) -> Domain::Config

        def initialize: (settings: Settings) -> void

        def process: -> Domain::Config

        def build_config: -> Domain::Config

        def base_config: -> Domain::Config

        private def name: -> String
        private def cool_off_time: -> duration
        private def threshold: -> (percentage | Integer)
        private def recovery_threshold: -> Integer
        private def window_size: -> duration?
        private def skipped_errors: -> Array[_ExceptionMatcher]
        private def tracked_errors: -> Array[_ExceptionMatcher]
        private def traffic_control: -> Domain::TrafficControl::Base
        private def traffic_recovery: -> Domain::TrafficRecovery::Base
        private def error_notifier: -> error_notifier
        private def notifiers: -> Array[state_transition_notifier]
        private def data_store: -> data_store
      end
    end
  end
end
