module Stoplight
  module Infrastructure
    module Notifier
      class FailSafe < Domain::StateTransitionNotifier
        attr_reader notifier: Domain::StateTransitionNotifier
        attr_reader error_notifier: error_notifier
        @circuit_breaker: Domain::Light?

        def initialize: (notifier: Domain::StateTransitionNotifier, error_notifier: error_notifier) -> void

        def notify: (Domain::Config, Domain::color, Domain::color, ?StandardError?) -> void

        def ==: (Object other) -> bool

        private def circuit_breaker: -> Domain::Light
      end
    end
  end
end
