module Stoplight
  module Infrastructure
    module Notifier
      class Logger
        include _StateTransitionNotifier
        include Generic[::Logger]

        def logger: -> ::Logger

        def put: (String message) -> void
      end
    end
  end
end
