module Stoplight
  class Admin
    class Panel
      module Helpers : Sinatra::Base
        STATE_TEMPLATES: Hash[Array[Domain::color | bool], Symbol]

        def dependencies: -> Dependencies
        def selected_light: (Array[LightSummary]) -> LightSummary?
        def find_light: (Array[LightSummary], String) -> LightSummary
        def state_template_for: (LightSummary) -> Symbol
        def system_url: (String system_id, String path) -> String
        def asset_path: (String) -> String
        def find_system: (String) -> Wiring::System
        def current_system_id: -> String
        def current_system: -> Wiring::System
        def turbo_frame_request?: -> bool
      end
    end
  end
end
