module Stoplight
  class Admin
    class Panel
      class LightSummary < Data
        attr_reader id: String
        attr_reader name: String
        attr_reader color: Domain::color
        attr_reader locked: bool

        def self.new: (
            id: String,
            name: String,
            color: Domain::color,
            locked: bool,
          ) -> instance

        def initialize: (
            id: String,
            name: String,
            color: Domain::color,
            locked: bool,
          ) -> void

        def locked?: -> bool
      end
    end
  end
end
