# frozen_string_literal: true

module Stoplight
  module Wiring
    class System
      class LightFactory < Wiring::LightFactory
        class InternalLightFactory
          include Domain::_LightFactory
        end

        attr_reader system: System

        def initialize: (system: System, config: Domain::Config) -> void
      end
    end
  end
end
