# frozen_string_literal: true

module Stoplight
  module Wiring
    class System
      class LightFactory < Wiring::LightFactory
        class InternalLightFactory
          include Domain::_LightFactory
        end

        attr_reader system: System
        attr_reader settings: Settings

        def initialize: (system: System, settings: Settings) -> void
      end
    end
  end
end
