module Stoplight
  module Wiring
    class DefaultConfiguration
      include _Configuration

      @config: Domain::Config
      @cool_off_time: optional[duration]
      @threshold: optional[percentage | Integer]
      @recovery_threshold: optional[Integer]
      @window_size: optional[duration?]
      @tracked_errors: optional[Array[_ExceptionMatcher] | _ExceptionMatcher]
      @skipped_errors: optional[Array[_ExceptionMatcher] | _ExceptionMatcher]
      @traffic_control: optional[traffic_control]
      @traffic_recovery: optional[traffic_recovery]
      @error_notifier: optional[error_notifier]
      @data_store: optional[data_store]
      @notifiers: optional[Array[state_transition_notifier]]

      def to_config!: -> Domain::Config

      private

      def tracked_errors: -> optional[Array[_ExceptionMatcher]]
      def skipped_errors: -> optional[Array[_ExceptionMatcher]]
      def traffic_control: -> optional[Domain::_TrafficControl]
      def traffic_recovery: -> optional[Domain::_TrafficRecovery]
    end
  end
end
