module Stoplight
  module Wiring
    class LightConfigurationDsl
      def initialize: (
        name: String,
        ?cool_off_time: optional[duration],
        ?threshold: optional[percentage | Integer],
        ?recovery_threshold: optional[Integer],
        ?window_size: optional[duration?],
        ?tracked_errors: optional[Array[Module] | Module],
        ?skipped_errors: optional[Array[Module] | Module],
        ?traffic_control: optional[traffic_control],
        ?traffic_recovery: optional[traffic_recovery],
      ) -> void

      def configure!: (Domain::Config default_config) -> Domain::Config

      attr_reader digest: Integer

      private

      attr_reader name: String
      attr_reader cool_off_time: optional[duration]
      attr_reader threshold: optional[percentage | Integer]
      attr_reader recovery_threshold: optional[Integer]
      attr_reader window_size: optional[duration?]
      attr_reader tracked_errors: optional[Array[Module]]
      attr_reader skipped_errors: optional[Array[Module]]
      attr_reader traffic_control: optional[Domain::_TrafficControl]
      attr_reader traffic_recovery: optional[Domain::_TrafficRecovery]

      def calculate_digest: -> Integer
      def errors_for_digest: (optional[Array[Module]]) -> optional[Array[String]]
    end
  end
end
