module Stoplight
  module Wiring
    class LightFactory < Domain::LightFactory
      attr_reader settings: Settings

      def initialize: (settings: Settings) -> void

      def validate_configuration!: -> void

      def ==: (untyped other) -> bool
      def eql: (untyped other) -> bool
      def hash: -> Integer

      def light_builder: (config: Domain::Config) -> LightBuilder
      def light_factory: -> Domain::LightFactory
    end
  end
end
