module Stoplight
  module Wiring
    class LightConfigurationDsl
      def initialize: (
        ?name: optional[String],
        ?cool_off_time: optional[duration],
        ?threshold: optional[percentage | Integer],
        ?recovery_threshold: optional[Integer],
        ?window_size: optional[duration?],
        ?tracked_errors: optional[Array[_ExceptionMatcher] | _ExceptionMatcher],
        ?skipped_errors: optional[Array[_ExceptionMatcher] | _ExceptionMatcher],
        ?traffic_control: optional[traffic_control],
        ?traffic_recovery: optional[traffic_recovery],
      ) -> void

      def configure!: (Domain::Config default_config) -> Domain::Config

      private

      attr_reader name: optional[String]
      attr_reader cool_off_time: optional[duration]
      attr_reader threshold: optional[percentage | Integer]
      attr_reader recovery_threshold: optional[Integer]
      attr_reader window_size: optional[duration?]
      attr_reader tracked_errors: optional[Array[_ExceptionMatcher]]
      attr_reader skipped_errors: optional[Array[_ExceptionMatcher]]
      attr_reader traffic_control: optional[Domain::_TrafficControl]
      attr_reader traffic_recovery: optional[Domain::_TrafficRecovery]
    end
  end
end
