module Stoplight
  module Wiring
    class LightFactory
      include Domain::_LightFactory
      attr_reader config: Domain::Config

      def initialize: (config: Domain::Config) -> void

      def eql: (untyped other) -> bool
      def hash: -> Integer

      def light_builder: (config: Domain::Config) -> LightBuilder
      def light_factory: -> Domain::_LightFactory
    end
  end
end
