module Stoplight
  module Wiring
    class Settings
      @name: option[String]
      attr_reader name: option[String]
      attr_reader cool_off_time: option[duration]
      attr_reader threshold: option[percentage | Integer]
      attr_reader recovery_threshold: option[Integer]
      attr_reader window_size: option[duration?]
      attr_reader skipped_errors: option[Array[_ExceptionMatcher]]
      attr_reader tracked_errors: option[Array[_ExceptionMatcher]]
      attr_reader traffic_control: option[traffic_control]
      attr_reader traffic_recovery: option[traffic_recovery]
      attr_reader error_notifier: option[error_notifier]
      attr_reader notifiers: option[Array[state_transition_notifier]]
      attr_reader data_store: option[data_store]

      EMPTY: Settings
      def self.empty: -> Settings

      def initialize: (
          name: option[String],
          cool_off_time: option[duration],
          threshold: option[percentage | Integer],
          recovery_threshold: option[Integer],
          window_size: option[duration?],
          skipped_errors: option[Array[_ExceptionMatcher]],
          tracked_errors: option[Array[_ExceptionMatcher]],
          traffic_control: option[traffic_control],
          traffic_recovery: option[traffic_recovery],
          error_notifier: option[error_notifier],
          notifiers: option[Array[state_transition_notifier]],
          data_store: option[data_store]
        ) -> void

      def extend_with: (
          ?name: optional[String],
          ?cool_off_time: optional[duration],
          ?threshold: optional[percentage | Integer],
          ?recovery_threshold: optional[Integer],
          ?window_size: optional[duration?],
          ?skipped_errors: optional[Array[_ExceptionMatcher]],
          ?tracked_errors: optional[Array[_ExceptionMatcher]],
          ?traffic_control: optional[traffic_control],
          ?traffic_recovery: optional[traffic_recovery],
          ?error_notifier: optional[error_notifier],
          ?notifiers: optional[Array[state_transition_notifier]],
          ?data_store: optional[data_store]
        ) -> Settings

      def empty?: -> bool
      def to_h: -> Hash[Symbol, option[untyped]]
    end
  end
end
