module Stoplight
  module Wiring
    class System
      include _System

      @name: String

      attr_reader light_factory: Domain::_LightFactory
      attr_reader lights: Concurrent::Map[String, [_Light, Domain::Config]]
      attr_reader system_config: Domain::Config

      def initialize: (config: Domain::Config) -> void
    end
  end
end
