module Stoplight
  module Domain
    # Holds the information about existing lights.
    # Each system has its own registry so you can query lights belonging to it.
    interface _Registry
      def ids: -> Array[String]
      def register: (Config) -> void
      def unregister: (String id) -> void
      def config_for: (String id) -> Hash[String, untyped]?
    end
  end
end
