module Stoplight
  module Domain
    type config_params = {
        name: String,
        cool_off_time: Integer,
        threshold: threshold,
        recovery_threshold: Integer,
        window_size: Integer?,
        tracked_errors: Array[StandardError],
        skipped_errors: Array[StandardError],
        traffic_control: TrafficControl::Base,
        traffic_recovery: TrafficRecovery::Base
      }
    type config_overrides = {
        ?name: String,
        ?cool_off_time: Integer,
        ?threshold: threshold,
        ?recovery_threshold: Integer,
        ?window_size: Integer?,
        ?tracked_errors: Array[StandardError],
        ?skipped_errors: Array[StandardError],
    }
  end
end
