module Stoplight
  module Infrastructure
    type error_notifier = ^(StandardError) -> void
    type notification_formatter = ^(Domain::Config light, Domain::color, Domain::color, StandardError?) -> String
  end
end
