module Stoplight
  module Notifier
    class Base
      include Domain::_StateTransitionNotifier
    end

    module Generic = Infrastructure::Notifier::Generic
    class IO = Infrastructure::Notifier::IO
    class Logger = Infrastructure::Notifier::Logger
  end
end
