module Stoplight
  module Domain
    module Strategies
      class RunStrategy[T]
        def execute:(
          ^(StandardError?) -> T,
          state_snapshot: StateSnapshot
        ) { () -> T } -> T
      end
    end
  end
end
