module Stoplight
  module Domain
    module Strategies
      class RunStrategy
        def execute: [T] (
          ^(StandardError?) -> T,
          state_snapshot: StateSnapshot
        ) { () -> T } -> T
      end
    end
  end
end
