module Stoplight
  module Infrastructure
    module Memory
      module Storage
        class UnboundedMetrics < Domain::Storage::Metrics
          attr_accessor consecutive_errors: Integer
          attr_accessor consecutive_successes: Integer
          attr_accessor last_error: Domain::Failure?
          attr_accessor last_success_at: Time?

          attr_reader mutex: Mutex
          attr_reader clock: Domain::Clock

          def initialize: (clock: Domain::Clock) -> void

          def last_error_at: -> Time?

          private def initialize_metrics: -> void
        end
      end
    end
  end
end
