module Stoplight
  class Admin
    module Actions
      class LockGreen < Action
        def call: (Sinatra::IndifferentHash) -> void

        private

        def light_names: (Sinatra::IndifferentHash) -> Array[String]
      end
    end
  end
end
