# frozen_string_literal: true

module Stoplight
  class Admin
    module Actions
      # This action removes a light's metadata from Redis
      class Remove < Action
        def call: (Sinatra::IndifferentHash) -> void

        private

        def light_names: (Sinatra::IndifferentHash) -> Array[String]
      end
    end
  end
end
