module Stoplight
  class Admin
    module Actions
      class Unlock < Action
        @config_registry: ConfigRegistry
        @storage: Wiring::System::Storage

        def initialize: (
            config_registry: ConfigRegistry,
            storage: Wiring::System::Storage
          ) -> void

        def call: (light_id: String) -> Domain::state
                | (light_id: String) -> void
      end
    end
  end
end
