module Stoplight
  module Domain
    module TrafficControl
      class ErrorRate
        include _TrafficControl

        NAME: :error_rate
        MIN_REQUESTS: Integer

        def initialize: () -> void
      end
    end
  end
end
