module Stoplight
  module Domain
    module Storage
      class Metrics
        def metrics_snapshot: () -> Domain::MetricsSnapshot

        def record_success: () -> void

        def record_failure: (StandardError error) -> void

        def clear: () -> void
      end
    end
  end
end
