module Stoplight
  module Domain
    module Storage
      class RecoveryLockToken < Domain::RecoveryLockToken
        attr_reader token: String

        def initialize: -> void
      end
    end
  end
end
