# frozen_string_literal: true

module Stoplight
  module Domain
    module Storage
      class RecoveryLock
        def acquire_lock: -> Storage::RecoveryLockToken?
        def release_lock: (Storage::RecoveryLockToken) -> void
      end
    end
  end
end
