module Stoplight
  interface _Light
    def name: -> String

    def state: -> Domain::state
    def color: -> Domain::color
    def run: [T] (
      ?(^(StandardError?) -> T)?,
      ?tracked_errors: optional[Array[Domain::_ExceptionMatcher] | Domain::_ExceptionMatcher],
      ?skipped_errors: optional[Array[Domain::_ExceptionMatcher] | Domain::_ExceptionMatcher]
    ) { () -> T } -> T
    def lock: (Domain::color) -> _Light
    def unlock: -> _Light
  end
end
