# frozen_string_literal: true

module Stoplight
  # A System is a composition root that groups related circuit breakers
  # with shared infrastructure configuration and defaults.
  interface _System
    def name: -> String

    def register: (
      String name,
      ?cool_off_time: optional[duration],
      ?threshold: optional[percentage | Integer],
      ?recovery_threshold: optional[Integer],
      ?window_size: optional[duration?],
      ?skipped_errors: optional[Array[Module] | Module],
      ?tracked_errors: optional[Array[Module] | Module],
      ?traffic_control: optional[traffic_control],
      ?traffic_recovery: optional[traffic_recovery]
    ) -> _Light

    def light: (String name) -> _Light

    def telemetry: -> _Telemetry
  end
end
