module Stoplight
  module Domain
    class Config < Data
      attr_reader threshold: percentage | Integer
      attr_reader window_size: duration?
      attr_reader tracked_errors: Array[_ExceptionMatcher]
      attr_reader skipped_errors: Array[_ExceptionMatcher]
      attr_reader name: String
      attr_reader cool_off_time: duration
      attr_reader recovery_threshold: Integer
      attr_reader traffic_control: _TrafficControl
      attr_reader traffic_recovery: _TrafficRecovery
      attr_reader error_notifier: error_notifier
      attr_reader notifiers: Array[state_transition_notifier]
      attr_reader data_store: data_store

      def self.new: (
          name: String,
          cool_off_time: duration,
          threshold: percentage | Integer,
          recovery_threshold: Integer,
          window_size: duration?,
          tracked_errors: Array[_ExceptionMatcher],
          skipped_errors: Array[_ExceptionMatcher],
          traffic_control: _TrafficControl,
          traffic_recovery: _TrafficRecovery,
          error_notifier: error_notifier,
          notifiers: Array[state_transition_notifier],
          data_store: data_store
        ) -> instance

      def initialize: (
          name: String,
          cool_off_time: duration,
          threshold: percentage | Integer,
          recovery_threshold: Integer,
          window_size: duration?,
          tracked_errors: Array[_ExceptionMatcher],
          skipped_errors: Array[_ExceptionMatcher],
          traffic_control: _TrafficControl,
          traffic_recovery: _TrafficRecovery,
          error_notifier: error_notifier,
          notifiers: Array[state_transition_notifier],
          data_store: data_store
        ) -> void

      def cool_off_time_in_milliseconds: () -> Integer

      def with: (
          ?name: optional[String],
          ?cool_off_time: optional[duration],
          ?threshold: optional[percentage | Integer],
          ?recovery_threshold: optional[Integer],
          ?window_size: optional[duration?],
          ?tracked_errors: optional[Array[_ExceptionMatcher]],
          ?skipped_errors: optional[Array[_ExceptionMatcher]],
          ?traffic_control: optional[_TrafficControl],
          ?traffic_recovery: optional[_TrafficRecovery],
          ?error_notifier: optional[error_notifier],
          ?notifiers: optional[Array[state_transition_notifier]],
          ?data_store: optional[data_store],
      ) -> Config | () -> Config
    end
  end
end
