module Stoplight
  module Domain
    class Light
      include _Light
      attr_reader green_run_strategy: Strategies::GreenRunStrategy
      attr_reader yellow_run_strategy: Strategies::YellowRunStrategy
      attr_reader red_run_strategy: Strategies::RedRunStrategy
      attr_reader state_store: _StateStore
      @name: String
      @lock_control: LockControl
      @error_tracking_policy: ErrorTrackingPolicy

      def initialize: (
        String name,
        green_run_strategy: Strategies::GreenRunStrategy,
        yellow_run_strategy: Strategies::YellowRunStrategy,
        red_run_strategy: Strategies::RedRunStrategy,
        state_store: _StateStore,
        lock_control: LockControl,
        error_tracking_policy: ErrorTrackingPolicy
      ) -> void

      private def state_strategy_factory: (color) -> _RunStrategy
      private def state_snapshot: -> StateSnapshot
    end
  end
end
