# frozen_string_literal: true

module Stoplight
  module Domain
    class System
      attr_reader name: String

      def light: (
        String name,
        ?cool_off_time: optional[duration],
        ?threshold: optional[percentage | Integer],
        ?recovery_threshold: optional[Integer],
        ?window_size: optional[duration?],
        ?skipped_errors: optional[Array[_ExceptionMatcher]],
        ?tracked_errors: optional[Array[_ExceptionMatcher]],
        ?traffic_control: optional[traffic_control],
        ?traffic_recovery: optional[traffic_recovery]
      ) -> Light
    end
  end
end
