# frozen_string_literal: true

module Stoplight
  module Infrastructure
    # steep:ignore:start
    module Postgres
      class DataStore
        class RecoveryLockToken
          attr_reader :light_name
          attr_reader :token

          # @param light_name [String]
          # @param token [String] the lock token generated by the store
          def initialize(light_name:, token:)
            @light_name = light_name
            @token = token
          end
        end
      end
    end
    # steep:ignore:end
  end
end
