name: 🚦Stoplight

on:
  pull_request:
  push:
    branches: [ main ]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  rubocop:
    name: Standard 👮
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Standard Ruby
        uses: standardrb/standard-ruby-action@eecb3f730879f5b8830705348c2961e5aa26de78 # v1.5.0
        with:
          autofix: false

  features:
    name: Features (${{ matrix.data-store }} Data Store and ${{ matrix.data-store-image }} Data Store image) 🥒
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data-store: [ 'Redis' ]
        data-store-image: [ 'redis:7.4', 'valkey/valkey:8-alpine' ]
        include:
          # Memory does not depend on the Data Store so we only want to run its suite once
          - data-store: 'Memory'
            data-store-image: 'redis:7.4'
    services:
      data-store:
        image: ${{ matrix.data-store-image }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@efbf473cab83af4468e8606cc33eca9281bb213f # v1.256.0
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Run Features
        run: bundle exec cucumber features/stoplight
        env:
          STOPLIGHT_REDIS_URL: 'redis://127.0.0.1:6379/0'
          STOPLIGHT_DATA_STORE: ${{ matrix.data-store }}
          CUCUMBER_PUBLISH_ENABLED: true

  spec:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    name: Specs on Ruby ${{ matrix.ruby }} with Data Store as ${{ matrix.data-store-image }} 💚
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data-store-image:
          - 'redis:6.2'
          - 'redis:7.2'
          - 'redis:7.4'
          - 'redis:8.0'
          - 'valkey/valkey:7.2-alpine'
          - 'valkey/valkey:8.1-alpine'
        ruby: [ '3.2', '3.3', '3.4' ]
    services:
      data-store:
        image: ${{ matrix.data-store-image }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@efbf473cab83af4468e8606cc33eca9281bb213f # v1.256.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Tests
        run: bundle exec rake spec
        env:
          STOPLIGHT_REDIS_URL: 'redis://127.0.0.1:6379/0'
      - name: Coveralls
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ruby-${{ matrix.ruby }}
          parallel: true
  finish:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
    needs: spec
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Coveralls Finished
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
