name: Docker 🐳
on:
  release:
    types: [published]

env:
  version: ${{ github.event.release.tag_name }}
  docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
  docker_password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  build:
    name: Build 🔧
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Checkout release
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ env.version }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            bolshakov/stoplight-admin:${{ env.version }}
            bolshakov/stoplight-admin:latest
          platforms: linux/amd64, linux/arm64
          context: .
          file: Dockerfile
